### ISSUE TITLE
Ignoring some errors generated by the linter

### ISSUE THREAD

**Issue by robojeb** [AtomLinter/Linter#187]
Some includes in my C++ project require me to specify additional include directories on the command line. Currently the linter marks these as errors. This is rather distracting when I am trying to find other issues. Would it be possible to add a way to silence errors?

**Comment by nesmyslny** [comment]
I'm facing the same problem. In my case, the 'problems' are AngularJS attributes. Using [linter-tidy](https://github.com/AtomLinter/linter-tidy) is kind of useless, because the file is littered with warnings (proprietary attributes; there's already feature request https://github.com/AtomLinter/linter-tidy/issues/1).

Wouldn't it be possible to provide a second regex to plugins. This one could describe lines to be ignored. So plugins could have some specialized ignore settings (e.g. proprietary attributes to ignore), build a regex and pass it to the linter.

SublimeLinter has such a [setting](http://sublimelinter.readthedocs.org/en/latest/linter_settings.html#ignore-match) and [syntastic](https://github.com/scrooloose/syntastic) has a setting to ignore tidy errors (`g:syntastic_html_tidy_ignore_errors`). Maybe there's some inspiration :wink:
