### ISSUE TITLE
Disable validation when no config file is present

### ISSUE THREAD

**Issue by Moeriki** [AtomLinter/Linter#188]
As suggested @dmnd https://github.com/AtomLinter/linter-jscs/issues/18

Do you concur this has a place in the Linter core?

**Comment by iam4x** [comment]
@dmnd @Moeriki I think this should be linter specific. Maybe I want to have `linter-jshint` lint everywhere, and `lint-jscs` only if a config file is present.

**Comment by hd-deman** [comment]
@iam4x I think this can be in Linter and can be overridden by specific linter.

**Comment by iam4x** [comment]
This will add work on Linter and on every linters too, and have to go to
Linter configuration and then every linters too for the user.

But if you guys prefere on Linter, I'm okay with it.

**Comment by dmnd** [comment]
Fair point @iam4x. I haven't fully thought this through, but I can imagine a nice "just works" default setup would satisfy the following:

 1. You can have a linter installed, but not active for projects/files for which it is irrelevant
 2. If a config file is present, a matching linter should definitely lint that project
 3. It might be desirable to have a "personal" linter that is active regardless of project settings (perhaps this is trigged by a config file in `~`? Or maybe it's always active like we have now)

Right now we assume every installed linter is active all the time. So 3 is satisfied, but 1 is difficult. Working across multiple projects that use different linters can be annoying (jshint vs eslint or pyflakes vs pylint)

It seems this setup is more complex than I had in mind when I made the suggestion in AtomLinter/linter-jscs#18.

**Comment by iam4x** [comment]
I think we can do some work on base Linter to have easy-implementation for linters to achieve this. Because right now it's kinda hard to have some thing clean, see https://github.com/AtomLinter/linter-jscs/commit/ff783059af77e79338354e88e95e7a05b67ca3dc

But imagine a linter that not take any config, will he be always un-activated? This may be a breaking change for every linters.

I think we should wait, think about an implementation for 2.0
