### ISSUE TITLE
Receive original file path

### ISSUE THREAD

**Issue by austincummings** [AtomLinter/Linter#213]
Rather than receiving a file path to the temporary file being linted, could I perhaps get an option whether to receive the real file path? This would be a wonderful option to have as I am trying to incorporate the Linter class in this package as the client of an async linting server for Dart.

**Comment by mieky** [comment]
I'm experiencing a similar issue with linter-tslint: tslint looks the directory hierarchy up for a configuration file tslint.json (normally on project root), but is unable to find one as it's only given a temporary file path.

Here you can see it fail finding tslint.json in the project root (because it isn't given the actual file path), and try to revert to ~/tslint.json, which isn't in place.
![screen shot 2015-01-08 at 20 09 36](https://cloud.githubusercontent.com/assets/299644/5667734/974b3034-9772-11e4-9772-49c74bf3a28d.png)

**Comment by SebastianEdwards** [comment]
Similar issue with linter-rubocop. .rubocop.yml allows different checks to be disabled by file path relative from the .rubocop.yml. E.g.

```yaml
Eval:
  Exclude:
    - spec/spec_helper.rb
```

This would work fine if the file being checked was in the correct position but not with the temp file path. Would gladly sacrifice "lint on change" to have the linter actually run correctly.

**Comment by matthewwithanm** [comment]
The temporary file approach also means that linter packages need to reimplement the discovery of config files usually done by the linter.
