### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'undefined'

### ISSUE THREAD

**Issue by ryanrhie9** [AtomLinter/Linter#314]
[Enter steps to reproduce below:]

1. ... Install "Language Dart" package in Settings/Packages
2. ... Uncaught Error occurred.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.7.3

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'undefined'

```
At fs.js:726

Error: ENOENT, no such file or directory 'undefined'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:155:14)
  at LinterDartAnalyzer.<anonymous> (/Users/jechol/.atom/packages/linter/lib/linter.coffee:56:8)
  at LinterDartAnalyzer.memoized [as _cachedStatSync] (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5569:32)
  at LinterDartAnalyzer.Linter.getCmdAndArgs (/Users/jechol/.atom/packages/linter/lib/linter.coffee:71:16)
  at LinterDartAnalyzer.Linter.lintFile (/Users/jechol/.atom/packages/linter/lib/linter.coffee:107:24)
  at /Users/jechol/.atom/packages/linter/lib/linter-view.coffee:141:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "disabledPackages": [
      "minimap"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.22.3
emmet, v2.2.1
language-dart, v0.1.1
less-autocompile, v0.3.3
linter, v0.7.3
linter-dartanalyzer, v0.3.1
linter-jshint, v0.1.0
linter-write-good, v0.2.2
monokai-seti, v0.4.0
seti-ui, v0.3.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment]
Thanks for the extra explanation @envygeeks, I will fix this soon

**Comment by dmnd** [comment]
I can't repro this. If I delete I file I have open in Atom, the Atom tab closes. @envygeeks are you sure about those repro steps?

**Comment by envygeeks** [comment]
@dmnd For me Atom doesn't always close the file, and sometimes it even bugs out when reopening a folder and will open a blank file that was deleted previously while it was closed, it is a bug that is for sure in Atom but I think it can be addressed here too as part of defensive coding (though I don't expect you to really care and I understand if you do not.)

Let me also imply that here lately it has not happened at all, actually not since the last time I updated has it happened so it might be worth it to just close this out for now and reopen it if it can be reproduced.

**Comment by dmnd** [comment]
Ok, I think I'l just close this for now as you suggest. Thanks for your help with this though!
