### ISSUE TITLE
Persistent Status Bar Counters

### ISSUE THREAD

**Issue by IanMitchell** [AtomLinter/Linter#412]
Hi, I was curious if it was possible to have the Error / Warning count on the status bar persist even when the count is 0? It looks like you're removing the elements at the moment, so I don't think I can override in my personal stylesheet. Is there another way to go about making them persist, or am I out of luck?

**Comment by dmnd** [comment]
I was trying to save space by hiding these since most of the time it says "0". But I understand that it's kind of weird to have it disappear completely since having it there provides an explicit reassurance that everything is working.

Would you be happier with the following:

* Error, warning and info counts disappear when zero
* When there are no errors, warnings or info messages, a grey dot with a 0 appears to show that there are no messages at all


This way we avoid having 3 dots and 3 zeroes most of the time, but we still make the state of having no lint messages explicit.

**Comment by IanMitchell** [comment]
What if instead of removing the DOM, you just use CSS to hide the warning / error elements? It would act the same way as it does now, but that way users have the ability to easily override and customize the behavior in their personal stylesheet without much maintenance / upkeep for you. I haven't extensively written Atom packages though, so not sure how difficult / feasible that solution would be.

**Comment by ababol** [comment]
I like @dmnd 'solution.

But if you want @IanMitchell , we can add a custom class like '.zeroError' when there is no error, this way it would be relatively easy for you to custom or to hide the element when there is no error (thank to your custom css), so everyone is happy.

Do you agree?

**Comment by IanMitchell** [comment]
I like his solution too, it just sounded like more work for you guys! I figured what I suggested would be easier to implement haha.
