### ISSUE TITLE
Linter: Next Message command moves the cursor in every editor, not just active editor

### ISSUE THREAD

**Issue by dmnd** [AtomLinter/Linter#424]
1. Open 2 different files in split panes
2. Make a lint error somewhere in each file
3. Put cursor at top of both files
4. Focus pane #1
5. Run command "Linter: Next Message"

Expected: Pane #1 jumps to the lint message, but pane #2 does not.
Observed: Both panes jump to their respective lint messages.

**Comment by dmnd** [comment]
@ababol updated this issue to make it clearer

**Comment by ababol** [comment]
@dmnd A ok, the dummy implementation would be to get every editor from all active pane and to look over on them to get the next error but this approach is clumsy.

I don't really know how to solve this issue, because if I am right, actually there is no way to share information between the different linter view from the different pane :/
