### ISSUE TITLE
add R linting

### ISSUE THREAD

**Issue by maxheld83** [AtomLinter/Linter#440]
that would be fantastic ...

**Comment by hd-deman** [comment]
@maxheld83 r u talking about [this](http://cran.r-project.org/web/packages/lint/index.html) tool?

**Comment by hd-deman** [comment]
I also find this http://yihui.name/formatR/

**Comment by maxheld83** [comment]
@hd-deman thanks for getting back so quickly.
I was thinking of @jimhester's [lintr](https://github.com/jimhester/lintr) package, which I find quite good.
I haven't systematically compared R linters though, I just came across (and liked) lintr, because it is already [implemented for Sublime Text](https://github.com/jimhester/SublimeLinter-contrib-lintr).

I guess `formatR` would be a different beast, since that actually *changes* (rather than lints) code.

**Comment by jimhester** [comment]
lintr has nearly all of the functionality of the existing R linting packages, ([lint](https://github.com/halpo/lint) and [svtools](http://cran.r-project.org/web/packages/svTools/index.html) were the main ones I was aware of), plus many more.

https://github.com/jimhester/lintr/issues/42 is for adding Atom integration (we already have Vim, Emacs, Sublime Text, RStudio).

It shouldn't be too much work to get Atom integration working if you base it off of the existing integrations.

I haven't done so yet because I do not use Atom myself and I wasn't sure how popular it was for R users, but at least different people have now requested it, so it is probably worthwhile.
