### ISSUE TITLE
Keybindings conflict with core atom pane split

### ISSUE THREAD

**Issue by sirianni** [AtomLinter/Linter#484]
`ctrl-k up/down` conflict with atom core's keymaps.json's `pane:split-up` and `pane:split-down`

**Comment by kankaristo** [comment]
The key bindings should be removed from Linter to remove the conflict with core, and `ctrl-k n/p` work fine.

As a workaround, you can unset the key bindings by adding this to your `keymap.cson`:
```
'.platform-linux atom-text-editor:not(.mini)':
  'ctrl-k up': 'unset!'
  'ctrl-k down': 'unset!'
```

(Replace `.platform-linux` with `.platform-windows` if you are on Windows)

This doesn't disable the `pane:split-*` key bindings, because they have broader scope.
