### ISSUE TITLE
node executable: false

### ISSUE THREAD

**Issue by steveoh** [AtomLinter/Linter#488]
Should I be interested in making this a true value? Is node => nodejs?

The `linter-python-pep8` linter is working in debug mode, ie, showing errors in the console but not displaying in the UI. I'm wondering if it is related to `node executable: false`.

https://gist.github.com/steveoh/339b4cf00bbb7d201b55

Can anyone offer some help.

**Comment by hd-deman** [comment]
this is absolutely not related to `node executable`.

**Comment by steveoh** [comment]
Can you offer anymore information @hd-deman

**Comment by hd-deman** [comment]
`node executable:true` used for packages that have use npm module as linter tool instead to ask user to install it. if [isNodeExecutable](https://github.com/AtomLinter/Linter/blob/master/lib/linter.coffee#L46) is true linter will [use nodejs](https://github.com/AtomLinter/Linter/blob/master/lib/linter.coffee#L118) that atom use to run itself. so the user does not need to install nodejs on system. this this option used for linter packages with nodejs based linter tool such as [linter-csslint](https://github.com/AtomLinter/linter-csslint), [linter-bootlint](https://github.com/AtomLinter/linter-bootlint) or [linter-jshint](https://github.com/AtomLinter/linter-jshint) but not for linter-python-pep8 because it use python to run linter, not nodejs)

**Comment by steveoh** [comment]
Thank you for describing that to me. That makes a lot of sense now. I should probably close this issue. I am not getting the lint results to show in the editor. Do you think that is an issue for here or the pep8 linter?

**Comment by hd-deman** [comment]
@steveoh can you provide your Linter config?

**Comment by steveoh** [comment]
@hd-deman in my `config.cson` i have

````cson
linter:
    showInfoMessages: true
    statusBar: "Show all errors"
    lintOnChangeInterval: 5000
    showErrorInline: false
    lintDebug: true
````

I do not see any settings for the `linter-python-pep8` package.

**Comment by hd-deman** [comment]
look like you not setup your `linter-pep8` package.
try to specify `pep8ExecutablePath` in linter-pep8 package settings.

**Comment by hd-deman** [comment]
I any way looks like this is related to `linter-pep8` package. Please open issue [here](https://github.com/AtomLinter/linter-pep8).

**Comment by steveoh** [comment]
@hd-deman I can see the linting errors in the console from running `debug: true`. That makes me think it is set up correctly. The linter or atom is not showing the errors. I don't know who's responsibility that is. I will try to install a more popular say js linter and see if I can get it to show errors.

**Comment by steveoh** [comment]
I installed linter-jshint and was able to see notifications in the atom gui. I will open an issue with pep8.
