### ISSUE TITLE
Toggle Linter

### ISSUE THREAD

**Issue by l4u** [AtomLinter/Linter#496]
is there a way to disable linter temporarily quickly via command palette?

**Comment by bluescreen10** [comment]
+1.

Sometimes when you're refactoring code it can be annoying those pop-ups. So I'd like to see if it can be globally enabled disabled via a shortcut or command palette

**Comment by sambaldwin** [comment]
:+1:

**Comment by bluescreen10** [comment]
What the command to toggle linter?

**Comment by steelbrain** [comment]
@bluescreen10 there isn't. Also if you want to disable linter temporarily, just disable it from settings menu. The latest version cleans everything up on deactivate so you shouldn't have any problems.

**Comment by AsaAyers** [comment]
All issues were closed because we switched to a rewrite of the linter. This is still a valid request and one that I'd like to have too.

I'm reopening it so maybe we'll get it done in the new linter. There will need to be some planning to figure out exactly how it should work. I think it should just disable for the current Editor, but I expect some disagreement. Disabling the linter from the settings panel is not really a solution for ignoring a file or a few files.

**Comment by steelbrain** [comment]
@AsaAyers would the latest change to allow toggling of panel be enough? or you want to disable the all the features of it?

**Comment by AsaAyers** [comment]
I'd want an option to go a step further and not even lint the current editor. I don't think it even needs a button, but a command that would cause it to clear all errors in the current editor and then never attempt linting again would solve the issue.

I don't think it should be something that persists. If you triggered it by mistake or change your mind you should be able to just close the tab and re-open the file.

**Comment by steelbrain** [comment]
@AsaAyers a whole map just appeared in my mind on how to implement this, so I think I'll do this one right after that click-to-jump feature.
