### ISSUE TITLE
Only show Linter panel errors for selected line

### ISSUE THREAD

**Issue by caleb531** [AtomLinter/Linter#587]
I noticed that Linter recently updated to v1.0, and this is one absolutely essential feature I really miss. The pre-1.0 option to limit visible panel errors to the selected line totally rocks, as I prefer to minimize distraction within my editor. Could this be added to v1?

Thanks,
Caleb

**Comment by willdady** [comment]
Came here to request exactly this. It would be great to be able to configure how many errors the panel shows. It currently seems to max-out at 7 lines where you can scroll to show more. Personally I'd only want a maximum of maybe 2 or 3 visible.

**Comment by basarat** [comment]
Prefer using `inline errors` and then disabling the error list at the bottom (requested here : https://github.com/AtomLinter/Linter/issues/589)

**Comment by AsaAyers** [comment]
If you click on the active tab the panel will now toggle and you're left with only your inline errors.

Considering the error is available inline, what would be the point of showing that error again at the bottom? Currently the panel serves as a complete list, but if it only shows the error you're on it's just duplicate information.

**Comment by basarat** [comment]
> If you click on the active tab the panel will now toggle and you're left with only your inline errors.

That *just* happened https://github.com/AtomLinter/Linter/pull/590 so no longer want the disabling feature :tada: :100: :rose: thanks!

**Comment by dthpham** [comment]
:+1: Same. I'd like an option to use the pre-1.0 method where warnings/errors are only displayed in the status bar when your cursor is on the offending line.

**Comment by k2b6s9j** [comment]
So can some one please explain this offending line in panel thing to me. I do not remember pre-v1 Linter having a panel that did any such thing, it did however have a bubble that showed the error your cursor was over. We have the bubble in this version, and a panel to show you all the errors in your file, and an panel for errors in your project.

**Comment by k2b6s9j** [comment]
Screenshots/mockups of what you have in mind would be incredibly helpful.

**Comment by dthpham** [comment]
@k2b6s9j Thanks. That's what I meant. Pre-1.0 style:

![1](http://i.imgur.com/dbW1fUz.png)
![2](http://i.imgur.com/L0hlSLJ.png)

**Comment by dsandstrom** [comment]
Currently, the bottom error panel shows errors for the entire file.  (I'm not talking about the status bar count, but the panel above that lists the linting errors.)  Previously to 1.0, there was an option to only show a bottom panel error for the line the cursor is on.

I prefer this approach over the inline error because it's less in the way.  In addition, I don't like having the error panel show all errors because I'm often using legacy code that will have a lot of linting errors.

**Comment by k2b6s9j** [comment]
@dthpham Thank you for the screen shot. This makes much more sense to me. So you want to bubble to be able to show you all the errors on the line, and not just the errors at a specific point. I think that's reasonable. Would it be okay if this were a toggle-able option. You'd press a certain keystroke, or press a menu option, or look it up in the command window, and the bubble would show errors for the entire line. Activate the toggle again and it would show errors for a particular point.

**Comment by robneu** [comment]
+1 to what @dsandstrom said. I find the inline errors to be way too distracting and the current version of the bottom panel is now almost totally useless to me with them disabled.

The previous behavior would display only the issue for the currently selected line. Showing all the issues in a given file isn't very helpful if you're not using the inline error display...

**Comment by steelbrain** [comment]
@robneu You can click the tabs twice to hide the panel by the way.

**Comment by robneu** [comment]
@steelbrain that's handy, but doing that doesn't really help with this issue. With the inline bubbles disabled and the bottom panel hidden, the only information available is the gutter bubble letting you know there's some kind of a problem on a particular line.

**Comment by steelbrain** [comment]
@robneu You can also click that gutter to jump to next error or map the command `linter:next-error` to buttons of your choice.

**Comment by robneu** [comment]
@steelbrain Clicking doesn't seem to do anything for me. I'll try a keymap, but it would really be nice if the old behavior returned. If a selected line has an error, why wouldn't you want to highlight that error in the bottom panel automatically?

I don't really understand the point of displaying every error in a file in a big list in the first place, but that may just be something related to my workflow vs how most people use a linter?

**Comment by k2b6s9j** [comment]
I'm down with highlighted the errors from the current line. Or giving them
some special indicator.

**Comment by steelbrain** [comment]
@robneu Are you sure you're using the latest version? We pushed the updates recently.
Also all the errors in a file makes sense, really, 'cause you are supposed to fix them and it helps finding them quickly. Making the panel show errors from current line only doesn't make sense 'cause that's what the bubble is for.

**Comment by robneu** [comment]
@steelbrain Yes, I'm on the latest. I think maybe I misunderstood you. Clicking the line number in the bottom panel will bring me to an error in the file. I was trying to click the bubble indicator in the file gutter to highlight the line in the bottom panel which doesn't seem to do anything.

The issue with the inline bubble is that I find it too distracting. Having the error display inline can make fixing it harder because the error can be related to how the code is being used. When the surrounding code is hidden by the error bubble, it slows me down. That's been my experience anyway.

Anyway, thanks for all the work that's gone into this rewrite. The overall formatting and everything else about the new linter is much better. :+1:

**Comment by steelbrain** [comment]
@robneu The inline bubble may be a distraction for some languages, but for others, like the c family of languages and flowjs and hacklang, it is used to show more information about that error, like a trace of where it was defined and where was it overriden. That's information that wouldn't look great if put in the bottom panel and would take too much space.

![screenshot from 2015-06-24 20 03 10](https://cloud.githubusercontent.com/assets/4278113/8345423/13725bda-1aac-11e5-9222-a60957f14ef7.png)

Here's an example of the bubble usage where one error in current file points shows a trace to other files. Clicking those positions would take you to that file:line:col

**Comment by robneu** [comment]
@steelbrain That makes sense. Personally, I'd still rather have the option to display that information at the bottom of the editor instead of inline, but I'm sure I'll get used to it inline eventually.

**Comment by bjmiller** [comment]
Adding another +1 to restore the pre-1.0 behavior.  It shouldn't be that hard to create and option to take all of the information in the pop up bubble, and simply put it in the bottom panel instead.

**Comment by stormwarning** [comment]
Echoing the request for single-line error display in the bottom panel. I'd argue that the inline bubble takes up more space than the panel, as it is obscuring other—possibly relevant—code, while code below the bottom panel can be scrolled to (especially if the Atom option "scroll past end" is enabled).

Personally, a status-bar–type area is where I instinctively look for detail about what I'm selecting/interacting with; ala Finder, browser windows, etc.

**Comment by steelbrain** [comment]
@stormwarning Soon you'll be able to peek below the bubble by holding a key of your choice. Ref: https://github.com/AtomLinter/Linter/pull/617

**Comment by robneu** [comment]
@steelbrain That's cool, but still not what is being asked for.

**Comment by AsaAyers** [comment]
> It shouldn't be that hard to create and option

You're correct, but we're also trying not to overly complicate things. We're not going to add an option for everything you can imagine, many other options have already been rejected.

You may also note that this issue is still open. It hasn't been rejected completely, but we aren't willing to rush to try to make everyone happy. If this gets done it needs to be done right and consistent with the rest of the linter.

We have tabs for `Current File` and `Project`. The quick solution would be to add a `Only the current line` tab, but it's obviously an ugly solution. So now someone will say "Just make `CurrentFile`" show the bubble text. Now `Project` doesn't make any sense. This is only a few quick things off the top of my head, but hopefully it helps demonstrate why "Just restore pre-1.0 behavior" is not as simple as it sounds.

**Comment by bjmiller** [comment]
That's a very pragmatic attitude, which I would normally agree with.  I only disagree with it here because you are being this circumspect about restoring a feature that used to exist in the previous version, and which people are clearly surprised is now missing.

**Comment by caleb531** [comment]
@AsaAyers I see the dilemma, and in a sudden plot twist, I agree with your reasoning. For what it's worth, I myself have decided to embrace the new inline tooltips. However, I still think it's good to have this discussion, and I leave it up to the rest of you to discuss/determine what's best. I no longer have a preference either way.

**Comment by robneu** [comment]
+1 to what @bjmiller said. I would also normally agree, but I really think the previous display option was less intrusive. Honestly, the linter is one of the primary reasons why I switched to Atom from Sublime. If it worked the way it does now I'm not sure I would have made the switch. 

I realize I'm just one person, but it seems that I'm not alone in this opinion. I'm still hoping that I'll get used to the inline errors but so far I still find it extremely annoying compared to the previous display.

**Comment by steelbrain** [comment]
@robneu The objective of linter is to help you make error-free programs. and If you'll suppress the bottom panel to only show the errors from current line how would you know the errors from the bottom of the file or places where you won't look.
IMHO it's a great design that the panel gives you a way to have a look at all the errors of the file and tooltip shows you the current error, while you can hold any key of your choice that you defined in the keymap to make it transparent ( https://github.com/AtomLinter/Linter/pull/617 ).

**Comment by AsaAyers** [comment]
We aren't saying no, just that we don't yet see a clear and reasonable path
between where we are and what's requested.

For what it's worth, I have an idea. I'll have to check it out when I'm not
on my phone.

**Comment by bjmiller** [comment]
I think that having the status bar show you the total number of lint fouls, while the panel above that only reflects only what currently is reflected in the tooltip, is a pretty good compromise.  You'll know that there are errors from the big red X in the statusbar, no matter where the cursor is.

I feel like the previous behavior is there in spirit through the tooltips.  But, where they're positioned is a bit too obtrusive and distracting for some people, and they'd rather have it in a panel that's affixed to the bottom.

@AsaAyers: Thank you for being open about this.  I do hope that I haven't come across as being too forceful.

**Comment by robneu** [comment]
:+1:

**Comment by stormwarning** [comment]
I appreciate that the issue is being considered and not just dismissed. Hopefully a solution/compromise can be found!

**Comment by JeanMertz** [comment]
:+1: for having current-line errors show up in the bottom pane, while not having a popup.

My personal reasons:

1. Inline popups are distracting
2. Working with legacy code makes the bottom pane useless (300+ errors, no way to quickly see the current error))

**Comment by AsaAyers** [comment]
> no way to quickly see the current error

This is exactly the purpose of the popup you turned off. IMO this is like turning off your monitor and then complaining that you can't see what your computer is doing.

> Working with legacy code makes the bottom pane useless (300+ errors

This portion I totally agree with, which is why we have multiple solutions.

1. click the active tab to hide the panel.
2. Run the `Linter: Toggle` command. It turns off the linter for the active tab

**Comment by JeanMertz** [comment]
@AsaAyers I get what you are saying with your first comment, but you are selectively commenting on my two reasons for requesting this feature.

Having popups show up on/below the current line is distracting to me, and thus while true that the purpose of the popup is to show the current error, it is also not an option for me, due to the distraction.

I'd rather have it show up at the bottom pane, so that I can *choose* if/when I want to look at the error (without requiring any action, besides moving my visual focus).

**Comment by JeanMertz** [comment]
Just wanted to say: awesome that this made it into the plugin. And the implementation is perfect (especially once https://github.com/AtomLinter/Linter/pull/655 is merged). Something for everyone without too much configuration bloat/confusion :+1:

**Comment by kepler0** [comment]
The Linter UI, specifically the bottom panel, is being redesigned on #1006. Please check out the proposed changes and voice your opinion.
