### ISSUE TITLE
Accessing the Linter object via services interface is broken.

### ISSUE THREAD

**Issue by radicaled** [AtomLinter/Linter#636]
According to package.json:

```
"providedServices": {
    "linter-plus-self": {
      "versions": {
        "0.1.0": "provideLinter"
      }
    }
  },
```

However, this is the code in `main.coffee`:

```
  provideLinter: ->
    @Linter
```

It should probably be `@instance`. As it is now, `provideLinter` returns null, so you cannot consume the main `Linter` object via services.

**Comment by steelbrain** [comment]
It's not `0.1.0`, It's `1.0.0`. :sweat_smile:

**Comment by radicaled** [comment]
I'm trying to get access to the Linter object service, not provide an interface to Linter. See the code snippets above.

**Comment by steelbrain** [comment]
Let me create an example quicky. Just a few minutes.

**Comment by steelbrain** [comment]
It's been fixed and a release has been pushed.

**Comment by radicaled** [comment]
Thanks mate.

**Comment by AsaAyers** [comment]
Why do you want to access the linter instance? We're providing it just
because we can and no one else has ever given a reason they might need it.

**Comment by steelbrain** [comment]
@AsaAyers They are using it in their `dart-tools` package to collect messages from an external daemon that doesn't care about editor saves and feed it to linter.

**Comment by AsaAyers** [comment]
Then we should provide a service for that, not just expose the internals of linter for any other package to poke at.

**Comment by steelbrain** [comment]
@AsaAyers I think our public methods are quite stable for other packages to use, and the global `atom` variable has all of the atom, instead of increasing the complexity and keeping the two things separate, they choose to expose the whole of it and then people use the Public API. and I haven't found any problems with it to date.

**Comment by AsaAyers** [comment]
You're still completely wrong. We should have a documented service that we know is exposed to others instead of just blindly exporting everything that shows up on the linter. Is it ok for them to call `deactivate`? No, it shouldn't be on the object we hand over. What about `addLinter` and `removeLinter`? Definitely not

It seems like you want to export an object that contains `getProjectMessages`, `setProjectMessages`, and `deleteProjectMessages`. That's all that should be exposed in this service.

**Comment by steelbrain** [comment]
Those few methods won't really work for everyone in my opinion.
They also need `eachEditorLinter`, `observeEditorLinter` and some other methods in `@views`.
and I am not sure if someone would ever call `deactivate` on a service they're consuming, and if they do that, then they suffer the consequences, not our problem.

The same knife can be used to cut apples or people's throats, You would blame the user not the person.

**Comment by AsaAyers** [comment]
Sorry, this shows your lack of experience managing such a project.

1. There is no documentation on what they can do with our current approach
2. linter is primarily internal. I will at some point refactor things and
break the service
3. You simply shouldn't expose things you don't want people messing with
because they will

If you want to expose a service, you should expose exactly the service you
want used.

**Comment by steelbrain** [comment]
@AsaAyers
I do plan on writing the documentation very soon.
Negative about Point 2, I have made sure that we don't have any redundant methods in the codebase.
About Point 3, It is ideal to not expose them, but there's nothing wrong if you would. 'cause If they were, then I am not sure that It won't be just me that would fit in your `lack of experience` circle, all of the atom core team and contributors will too.

Also I think our public API is quite stable, I am even trying to connect with abe of atom-minimap to request him for a minimap plugin for Linter. I still agree that we need documentation but there's nothing wrong with exposing all of us.

**Comment by AsaAyers** [comment]
You're never going to convince me. I've been doing this for enough years to
know this is a VERY bad idea. When I have some time I'll extract it into a
proper service.

**Comment by steelbrain** [comment]
Looking forward to your PR :) 
I'm 100% cool with it if you wanna wrap the externals of `@instance` and put them in a new object.

**Comment by steelbrain** [comment]
Also I've added some Public API to the wiki [here][1].

[1]:https://github.com/AtomLinter/Linter/wiki/Public-API
